config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
lfba01:
  target: dev
  outputs:
    dev:
      dbname: lfba01
      host: 10.6.0.115
      pass: pgpasswrd
      port: 5432
      schema: dbo
      threads: 8
      type: postgres
      user: pguser
